#!/usr/bin/env ruby
# Call with: sudo ./install [--symlink]

require 'pathname'

def install_file(name)
	git_path = %x(which git).rstrip

    if File.symlink? git_path
        git_path = Pathname.new(git_path).realpath.to_s
    end

	git_root = File.split(File.split(git_path)[0])[0]
	gitcore_path = File.join(git_root, 'libexec/git-core')

	source_name = name
	symlink_name = File.basename(name, File.extname(name))
	install_path = File.join(gitcore_path, symlink_name)

	if ARGV[0] == '--symlink' then
	    script_path = File.join(Dir.pwd, "#{source_name}")
	    %x(ln -s #{script_path} #{install_path})
	else
	    %x(cp #{source_name} #{install_path})
	    %x(chmod +x #{install_path})
	end
end


install_file 'git-lib.rb'
install_file 'git-split-lib.sh'
